- name: Information
  hosts: ACI_APIC
  vars:
    tenant: Ansible_Dev_tenant
    description: Ansible_Dev_Environment
    vrf: Ansible_Dev_VRF
    bd: Ansible_Dev_BD
    ap: Ansible_Prod_Application_Profile
    epg: Ansible_EPG
  connection: local
  gather_facts: no

  tasks:

    - name: Add End Point Group App One
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: "{{EPG}}"
        description: "{{description}}"
        bd: "{{bd}}"
        ap: "{{ap}}"
        preferred_group: yes
        state: present
      delegate_to: localhost