- name: Information
  hosts: ACI_APIC
  vars:
    tenant: Ansible_Dev_tenant
    description: Ansible_Dev_Environment
    vrf: Ansible_Dev_VRF
    bd: Ansible_Dev_BD
    ap: Ansible_Prod_Application_Profile
  connection: local
  gather_facts: no

  tasks:

    - name: Add A New Application Profile
      aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        ap: "{{ap}}"
        description: "{{description}}"
        state: present
      delegate_to: localhost   