- name: Play 1
  hosts: ACI_APIC
  vars:
    tenant: Ansible_Dev_tenant
    bd: Ansible_Dev_BD
    vrf: Ansible_Dev_VRF
    ap: Ansible_Dev_Application_Profile
    description: Ansible_Dev_Environment
  connection: local
  gather_facts: no

  tasks:

    - name: Add A Tenant
      aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        description: Production tenant
        validate_certs: no
        state: present
      delegate_to: localhost

    - name: Add A VRF
      aci_vrf:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        vrf: "{{vrf}}"
        tenant: "{{tenant}}"
        description: "{{description}}"
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: present
      delegate_to: localhost

    - name: Add Bridge Domain
      aci_bd:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        bd: "{{bd}}"
        mac_address: 00:00:00:11:11:11
        vrf: "{{vrf}}"
        state: present
      delegate_to: localhost

    - name: Add A New Application Profile
      aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        ap: "{{ap}}"
        description: "{{description}}"
        state: present
      delegate_to: localhost      

    - name: Add A New Virtual Domain
      aci_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        domain: Ansible_Dev_VCENTER
        domain_type: vmm
        vm_provider: vmware
        state: present
      delegate_to: localhost

    - name: Add A New Layer 3 External Domain
      aci_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        domain: L3_External
        domain_type: l3dom
        state: present
      delegate_to: localhost

    - name: Add A New Contract
      aci_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        contract: WEB_to_APP
        description: "{{description}}"
        scope: application-profile
        state: present
        validate_certs: no
      delegate_to: localhost

    - name: Add A New Contract
      aci_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        contract: APP_to_DB
        description: "{{description}}"
        scope: application-profile
        validate_certs: no
        state: present
      delegate_to: localhost

    - name: Add A New Contract
      aci_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        contract: Web_to_L3
        description: "{{description}}"
        scope: application-profile
        validate_certs: no
        state: present
      delegate_to: localhost

    - name: Add A New Contract
      aci_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        contract: Web_to_L3
        description: "{{description}}"
        scope: application-profile
        validate_certs: no
        state: present
      delegate_to: localhost

    - name: Add End Point Group App One
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: Web_EPG_One
        description: "{{description}}"
        bd: "{{bd}}"
        ap: "{{ap}}"
        preferred_group: yes
        state: present
      delegate_to: localhost

    - name: Add End Point Group App One
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: App_EPG_One
        description: "{{description}}"
        bd: "{{bd}}"
        ap: "{{ap}}"
        preferred_group: yes
        state: present
      delegate_to: localhost

    - name: Add End Point Group App One
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: DB_EPG_One
        description: "{{description}}"
        bd: "{{bd}}"
        ap: "{{ap}}"
        preferred_group: yes
        state: present
      delegate_to: localhost

    - name: Attach Web EPG to VMM Domain
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: Web_EPG_One
        ap: "{{ap}}"
        domain: Ansible_Dev_VCENTER
        domain_type: vmm
        vm_provider: vmware
        state: present
      delegate_to: localhost

    - name: Attach App EPG to VMM Domain
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: App_EPG_One
        ap: "{{ap}}"
        domain: Ansible_Dev_VCENTER
        domain_type: vmm
        vm_provider: vmware
        state: present
      delegate_to: localhost

    - name: Attach DB EPG to VMM Domain
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: DB_EPG_One
        ap: "{{ap}}"
        domain: Ansible_Dev_VCENTER
        domain_type: vmm
        vm_provider: vmware
        state: present
      delegate_to: localhost

    - name: Add A New Contract To Web EPG to App EPG
      aci_epg_to_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: Web_EPG_One
        ap: "{{ap}}"
        contract: WEB_to_APP
        contract_type: provider
        state: present
      delegate_to: localhost

    - name: Add A New Contract To App EPG to Web EPG
      aci_epg_to_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: App_EPG_One
        ap: "{{ap}}"
        contract: WEB_to_APP
        contract_type: consumer
        state: present
      delegate_to: localhost

    - name: Add A New Contract To App EPG to DB EPG
      aci_epg_to_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: App_EPG_One
        ap: "{{ap}}"
        contract: APP_to_DB
        contract_type: provider
        state: present
      delegate_to: localhost

    - name: Add A New Contract To DB EPG to App EPG
      aci_epg_to_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: "{{tenant}}"
        epg: DB_EPG_One
        ap: "{{ap}}"
        contract: APP_to_DB
        contract_type: consumer
        state: present
      delegate_to: localhost

    - name: Add A New Layer 3 Out
      aci_l3out:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        l3out: Layer_3_Out
        domain: L3_External
        vrf: "{{vrf}}"
        route_control: export
        l3protocol: ospf
        validate_certs: no
        state: present
      delegate_to: localhost

