- name: Information
  hosts: ACI_APIC
  vars:
    tenant: Ansible_Dev_tenant
    description: Ansible_Dev_Environment
    vrf: Ansible_Dev_VRF
    bd: Ansible_Dev_BD
    ap: Ansible_Prod_Application_Profile
    contract: Ansible_Contract
  connection: local
  gather_facts: no

  tasks:

    - name: Add A New Contract
      aci_contract:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: "{{tenant}}"
        contract: "{{contrac}}"
        description: "{{description}}"
        scope: application-profile
        validate_certs: no
        state: present
      delegate_to: localhost