- name: Play 1
  hosts: ACI_APIC
  connection: local
  gather_facts: no

  tasks:

    - name: Create a Snapshot
      aci_config_snapshot:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        export_policy: config_backup
        max_count: 10
        description: Backup configuration before new configs are applied

